atomic: consolidated 7 & 8 templates and isolinux & grub menus

diff --git a/etc/ack-template-post b/etc/ack-template-post
--- a/etc/ack-template-post
+++ b/etc/ack-template-post
@@ -1,23 +1,27 @@
 #!/bin/bash
 
-PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
+#
+# globals
+#
 
-if [ "$DEBUG" == "" ]; then
+PATH=/usr/sbin:/sbin:/usr/bin:/bin
+
+ACK_BUILD_ISO=##ACK_BUILD_ISO##
+ACK_BUILD_MAJOR=##ACK_BUILD_MAJOR##
+ACK_CLIENT_RECOVERY=##ACK_CLIENT_RECOVERY##
+
+if [ "${DEBUG}" == "" ]; then
     declare -i DEBUG=##ACK_CLIENT_DEBUG##
 else
-    declare -i DEBUG=$DEBUG
+    declare -i DEBUG=${DEBUG}
 fi
 
 TEMPLATE_ID="default"
 
 echo
-echo "ack-template-post-${TEMPLATE_ID}"
-echo
+echo "+ ack-template-post-${TEMPLATE_ID} (${ACK_BUILD_ISO})"
 
-ACK_BUILD_ISO=##ACK_BUILD_ISO##
-ACK_CLIENT_RECOVERY=##ACK_CLIENT_RECOVERY##
-
-echo "$(date) - $(basename "${ACK_BUILD_ISO}")" > /etc/ack-release
+echo "$(basename "${ACK_BUILD_ISO}")" > /etc/ack-release
 
 if [ -r "/mnt/sysimage/etc/passwd" ]; then
     # for testing via pre shell
@@ -27,7 +31,14 @@ else
     ROOT_DIR=""
 fi
 
-# authorized_keys
+if [ ${#ROOT_DIR} -gt 0 ]; then
+    echo "ROOT_DIR  = ${ROOT_DIR}"
+    echo
+fi
+
+echo
+echo "+ update authorized_keys"
+
 SSH_DIR="${ROOT_DIR}/root/.ssh"
 
 mkdir -p "${SSH_DIR}"
@@ -39,12 +50,72 @@ ACK_SSH_AUTHORIZED_KEYS=##ACK_SSH_AUTHORIZED_KEYS##
 if [ "${ACK_SSH_AUTHORIZED_KEYS}" != "" ]; then
     >"${SSH_DIR}/authorized_keys"
     for ACK_SSH_AUTHORIZED_KEY in "${ACK_SSH_AUTHORIZED_KEYS[@]}"; do
-        echo $ACK_SSH_AUTHORIZED_KEY >> "${SSH_DIR}/authorized_keys"
+        echo ${ACK_SSH_AUTHORIZED_KEY} >> "${SSH_DIR}/authorized_keys"
     done
     chmod 0600 "${SSH_DIR}"/authorized_keys
 fi
 
+echo
+echo "+ curl & copy client files"
+echo
+
+# file,owner,mode; default is root:root 0644
+CLIENT_FILES=()
+CLIENT_FILES+=("/etc/colordiffrc")
+CLIENT_FILES+=("/etc/shells")
+CLIENT_FILES+=("/etc/sudoers,root:root,0400")
+CLIENT_FILES+=("/etc/ssh/ssh_config,root:root,0644")
+CLIENT_FILES+=("/etc/ssh/sshd_config,root:root,0600")
+CLIENT_FILES+=("/etc/profile.d/aliases.sh")
+CLIENT_FILES+=("/etc/profile.d/editor.sh")
+CLIENT_FILES+=("/etc/profile.d/prompt.sh")
+CLIENT_FILES+=("/etc/profile.d/root.sh")
+CLIENT_FILES+=("/etc/profile.d/timezone.sh")
+CLIENT_FILES+=("/etc/profile.d/whom.sh")
+CLIENT_FILES+=("/etc/profile.d/zzz-path.sh")
+CLIENT_FILES+=("/root/.ssh/config,root:root,0600")
+
+for CLIENT_FILE_DATA in "${CLIENT_FILES[@]}"; do
+    CLIENT_FILE=${CLIENT_FILE_DATA%%,*}
+
+    CLIENT_FILE_BASENAME="$(basename "${CLIENT_FILE}")"
+    URL="##ACK_CLIENT_INSTALL_URL##/file/${TEMPLATE_ID}/${CLIENT_FILE}"
+    HTTP_CODE=$(curl --silent -k --write-out "%{http_code}" "${URL}" -o "/tmp/${CLIENT_FILE_BASENAME}")
+
+    if [ "${HTTP_CODE}" != "200" ]; then
+        echo "ERROR: curl '${URL}' failed (HTTP_CODE=${HTTP_CODE})"
+    else
+        CLIENT_FILE_OWNER=${CLIENT_FILE_DATA#*,}
+        CLIENT_FILE_OWNER=${CLIENT_FILE_OWNER%,*}
+
+        if [ "${CLIENT_FILE_OWNER}" == "${CLIENT_FILE}" ]; then
+            CLIENT_FILE_OWNER="root:root"
+        fi
+
+        CLIENT_FILE_MODE=${CLIENT_FILE_DATA##*,}
+        if [ "${CLIENT_FILE_MODE}" == "${CLIENT_FILE}" ] || [ "${CLIENT_FILE_MODE}" == "${CLIENT_FILE_OWNER}" ]; then
+            CLIENT_FILE_MODE="0644"
+        fi
+
+        echo "CLIENT_FILE  = ${CLIENT_FILE} (${HTTP_CODE}) [${CLIENT_FILE_MODE},${CLIENT_FILE_OWNER}]"
+
+        if [ "${HTTP_CODE}" == "200" ]; then
+            cp "/tmp/${CLIENT_FILE_BASENAME}" "${CLIENT_FILE}"
+            if [ $? -eq 0 ]; then
+                chown "${CLIENT_FILE_OWNER}" "${CLIENT_FILE}"
+                chmod "${CLIENT_FILE_MODE}" "${CLIENT_FILE}"
+            fi
+            rm -f "/tmp/${CLIENT_FILE_BASENAME}"
+        fi
+    fi
+
+done
+
 if [ ${ACK_CLIENT_RECOVERY} -eq 0 ]; then
+
+    echo
+    echo "+ install recovery partition & boot files"
+    echo
 
     # boot recovery partition
     BOOT_DIR="${ROOT_DIR}/boot"
@@ -52,125 +123,111 @@ if [ ${ACK_CLIENT_RECOVERY} -eq 0 ]; then
 
     if [ -d "${BOOT_DIR}" ] && [ -d "${RECOVERY_DIR}" ]; then
 
-        HTTP_CODE=$(curl --silent -k --write-out "%{http_code}" "##ACK_CLIENT_RELEASE_URL##/${ACK_BUILD_ISO}" -o "${RECOVERY_DIR}/${ACK_BUILD_ISO}")
+        URL="##ACK_CLIENT_RELEASE_URL##/${ACK_BUILD_ISO}"
+        HTTP_CODE=$(curl --silent -k --write-out "%{http_code}" "${URL}" -o "${RECOVERY_DIR}/${ACK_BUILD_ISO}")
 
-        if [ "${HTTP_CODE}" == "200" ] && [ -s "${RECOVERY_DIR}/${ACK_BUILD_ISO}" ]; then
-            unset -v HTTP_CODE
+        if [ "${HTTP_CODE}" != "200" ]; then
+            echo "ERROR: curl '${URL}' failed (HTTP_CODE=${HTTP_CODE})"
+        else
+            if [ ! -s "${RECOVERY_DIR}/${ACK_BUILD_ISO}" ]; then
+                echo "ERROR: '${RECOVER_DIR}/${ACK_BUILD_ISO}' is zero bytes"
+            else
 
-            GRUB_CFG="$(find "${BOOT_DIR}" -type f -name grub.cfg | head -1)"
-            echo "GRUB_CFG = ${GRUB_CFG}"
+                GRUB_CFG="$(find "${BOOT_DIR}" -type f -name grub.cfg | head -1)"
+                if [ ! -r "${GRUB_CFG}" ]; then
+                    echo "ERROR: '${GRUB_CFG}' file not readable"
+                else
+                    echo "GRUB_CFG = ${GRUB_CFG}"
 
-            if [ -d "${BOOT_DIR}/grub2" ] && [ -r "$GRUB_CFG" ]; then
-                GRUB_DIR="$(dirname "${GRUB_CFG}")"
-                echo "GRUB_DIR = ${GRUB_DIR}"
-
-                CUSTOM_CFG="custom.cfg"
-                HTTP_CODE=$(curl --silent -k --write-out "%{http_code}" "##ACK_CLIENT_INSTALL_URL##/?build=##ACK_CLIENT_BUILD_URI##&install=##ACK_CLIENT_INSTALL_URI##&include=ack-template-recovery-grub" -o "/tmp/${CUSTOM_CFG}")
-
-                if [ "${HTTP_CODE}" == "200" ]; then
-                    unset -v HTTP_CODE
-
-                    if (grep -q ^menuentry "/tmp/${CUSTOM_CFG}"); then
-
-                        if [ -d /sys/firemware/efi ]; then
-
-                        # uefi
-                        cat "/tmp/${CUSTOM_CFG}" | sed \
-                            -e 's#BIOS#UEFI#g' \
-                            > "${GRUB_DIR}/custom.cfg"
-
+                    if [ ! -d "${BOOT_DIR}/grub2" ]; then
+                        echo "ERROR: '${BOOT_DIR}/grub2' directory not found"
                     else
+                        GRUB_DIR="$(dirname "${GRUB_CFG}")"
+                        echo "GRUB_DIR = ${GRUB_DIR}"
 
-                        # bios
-                        cat "/tmp/${CUSTOM_CFG}" | sed \
-                            -e 's#UEFI#BIOS#g' \
-                            -e 's#initrdefi#initrd#g' \
-                            -e 's#linuxefi#linux#g' \
-                            > "${GRUB_DIR}/custom.cfg"
+                        CUSTOM_CFG="custom.cfg"
+                        URL="##ACK_CLIENT_INSTALL_URL##/?build=##ACK_CLIENT_BUILD_URI##&install=##ACK_CLIENT_INSTALL_URI##&include=ack-template-recovery-grub&recovery"
+                        HTTP_CODE=$(curl --silent -k --write-out "%{http_code}" "${URL}" -o "/tmp/${CUSTOM_CFG}")
 
+                        if [ "${HTTP_CODE}" != "200" ]; then
+                            echo "ERROR: curl '${URL}' failed (HTTP_CODE=${HTTP_CODE})"
+                        else
+                            if [ -r "/tmp/${CUSTOM_CFG}" ]; then
+                                if (grep -q ^[[:blank:]]*menuentry "/tmp/${CUSTOM_CFG}"); then
+
+                                    if [ -d /sys/firemware/efi ]; then
+
+                                    # uefi
+                                    cat "/tmp/${CUSTOM_CFG}" | sed \
+                                        -e 's!BIOS!UEFI!g' \
+                                        > "${GRUB_DIR}/custom.cfg"
+
+                                else
+
+                                    # bios
+                                    cat "/tmp/${CUSTOM_CFG}" | sed \
+                                        -e 's!UEFI!BIOS!g' \
+                                        -e 's!initrdefi!initrd!g' \
+                                        -e 's!linuxefi!linux!g' \
+                                        -e 's!,gpt!,msdos!g' \
+                                        > "${GRUB_DIR}/custom.cfg"
+
+                                    fi
+
+                                    cat "${GRUB_DIR}/custom.cfg" && echo
+
+                                    echo "+ grub2-mkconfig -o ${GRUB_CFG}"
+                                    echo
+                                    grub2-mkconfig -o "${GRUB_CFG}"
+
+                                    mkdir -p "${RECOVERY_DIR}/grub2"
+                                    cp "${GRUB_CFG}" "${RECOVERY_DIR}/grub2"
+                                    cp "${GRUB_DIR}/custom.cfg" "${RECOVERY_DIR}/grub2"
+                                else
+                                    echo "ERROR: '/tmp/${CUSTOM_CFG}' has no menuentry"
+                                fi
+                            else
+                                echo "ERROR: '/tmp/${CUSTOM_CFG}' file not found readable"
+                            fi
                         fi
-
-                    # common
-
-                    sed -i \
-                        -e "s+##INITRAMFS##+${INITRAMFS}+g" \
-                        -e "s+##VMLINUZ##+${VMLINUZ}+g" \
-                        "${GRUB_DIR}/custom.cfg"
-
-                    cat "${GRUB_DIR}/custom.cfg" && echo
-
-                    echo "+ grub2-mkconfig -o ${GRUB_CFG}"
-                    grub2-mkconfig -o "${GRUB_CFG}"
-
-                    cp "${GRUB_CFG}" "${RECOVERY_DIR}"
-                    cp "${GRUB_DIR}/custom.cfg" "${RECOVERY_DIR}"
-
-                    echo
                     fi
-
                 fi
-
-                unset -v HTTP_CODE
             fi
         fi
-
     fi
 fi
 
-# misc
+echo
+echo "+ apply misc mods"
+echo
+
+# allow root logins
+touch ${ROOT_DIR}/root/.Allow
+
+# update /etc/shadow & /etc/gshadow
 pwconv 2> /dev/null
 grpconv 2> /dev/null
 
+# empty TERM=screen* PROMPT_COMMAND
 touch /etc/sysconfig/bash-prompt-screen
 chmod 0755 /etc/sysconfig/bash-prompt-screen
 
-# file,owner,mode; default is root:root 0644
-CUSTOM_FILES=()
-CUSTOM_FILES+=("/etc/colordiffrc")
-CUSTOM_FILES+=("/etc/shells")
-CUSTOM_FILES+=("/etc/sudoers,root:root,0400")
-CUSTOM_FILES+=("/etc/ssh/ssh_config,root:root,0644")
-CUSTOM_FILES+=("/etc/ssh/sshd_config,root:root,0600")
-CUSTOM_FILES+=("/etc/profile.d/aliases.sh")
-CUSTOM_FILES+=("/etc/profile.d/editor.sh")
-CUSTOM_FILES+=("/etc/profile.d/prompt.sh")
-CUSTOM_FILES+=("/etc/profile.d/root.sh")
-CUSTOM_FILES+=("/etc/profile.d/timezone.sh")
-CUSTOM_FILES+=("/etc/profile.d/whom.sh")
-CUSTOM_FILES+=("/etc/profile.d/zzz-path.sh")
-CUSTOM_FILES+=("/root/.ssh/config,root:root,0600")
-
-for CUSTOM_FILE_DATA in "${CUSTOM_FILES[@]}"; do
-    CUSTOM_FILE=${CUSTOM_FILE_DATA%%,*}
-
-    CUSTOM_BASENAME="$(basename "${CUSTOM_FILE}")"
-    HTTP_CODE=$(curl --silent -k --write-out "%{http_code}" "##ACK_CLIENT_INSTALL_URL##/file/${TEMPLATE_ID}/${CUSTOM_FILE}" -o "/tmp/${CUSTOM_BASENAME}")
-
-    CUSTOM_OWNER=${CUSTOM_FILE_DATA#*,}
-    CUSTOM_OWNER=${CUSTOM_OWNER%,*}
-
-    if [ "${CUSTOM_OWNER}" == "${CUSTOM_FILE}" ]; then
-        CUSTOM_OWNER="root:root"
-    fi
-
-    CUSTOM_MODE=${CUSTOM_FILE_DATA##*,}
-    if [ "${CUSTOM_MODE}" == "${CUSTOM_FILE}" ] || [ "${CUSTOM_MODE}" == "${CUSTOM_OWNER}" ]; then
-        CUSTOM_MODE="0644"
-    fi
-
-    echo "CUSTOM_FILE  = ${CUSTOM_FILE} (${HTTP_CODE}) [${CUSTOM_MODE},${CUSTOM_OWNER}]"
-
-    if [ "${HTTP_CODE}" == "200" ]; then
-        cp "/tmp/${CUSTOM_BASENAME}" "${CUSTOM_FILE}"
-        if [ $? -eq 0 ]; then
-            chown "${CUSTOM_OWNER}" "${CUSTOM_FILE}"
-            chmod "${CUSTOM_MODE}" "${CUSTOM_FILE}"
-        fi
-        rm -f "/tmp/${CUSTOM_BASENAME}"
-    fi
-
-    unset -v HTTP_CODE
-done
+echo
+echo "+ remove files"
 echo
 
-touch ${ROOT_DIR}/root/.Allow
+REMOVES=()
+REMOVES+=("/root/anaconda-ks.cfg")
+REMOVES+=("/root/original-ks.cfg")
+REMOVES+=("/tmp/custom.cfg")
+
+for REMOVE in "${REMOVES[@]}"; do
+    if [ -e "${REMOVE}" ]; then
+        echo "REMOVE  = ${REMOVE}"
+        if [ -d "${REMOVE}" ]; then
+            rm -rf "${REMOVE}"
+        else
+            rm -f "${REMOVE}"
+        fi
+    fi
+done
